#!/usr/bin/env python3
"""fabledocs.py — turn the Fable quota a run already spent into a durable artifact.

The scoperoute reports are metadata-only (FR4) — they never store Fable's response
text. But every `--probe code`/`arch` component was probed through `claude -p`, whose
full transcript is pinned under the run's own workdir. This stage reads those
transcripts and writes one structured `<repo>/_fable/fable-architecture-review.md` per
probed project: Fable's actual architectural review of each component.

It runs by DEFAULT after an arch/code run (opt out with --no-fable-docs). Because the
engine now records the probe workdir + the component inventory per row (schema v2), this
is deterministic: no globbing ~/.claude, no guessing which transcript belongs to which
project.

Privacy: the review prose is exactly what the user asked to keep. We never emit a
refusal's explanation URL, never write categories, and the shareable CSV is untouched.

Stdlib only.
"""
from __future__ import annotations

import glob
import json
import os
import re
from pathlib import Path

import transcript as T   # session_dir(workdir) -> where this run's probes were written

IMPROVE_HEAD_ARCH = "You are reviewing the architecture of a software component"
IMPROVE_HEAD_CODE = "You are reviewing a software component and suggesting concrete impro"
SUMMARY_HEAD = "Below is a recon of a project's components"
CURATE_HEAD = "Below are components of a project. Each has an architecture summary"
FABLE = "claude-fable-5"
SYNTH = ("<synthetic>", None, "")


# ---------------------------------------------------------------- transcript reading

def _load(path):
    out = []
    try:
        for line in open(path, encoding="utf-8"):
            line = line.strip()
            if line:
                try:
                    out.append(json.loads(line))
                except ValueError:
                    pass
    except OSError:
        pass
    return out


def _msg_text(m):
    c = m.get("content")
    if isinstance(c, str):
        return c
    if isinstance(c, list):
        return "\n".join(b.get("text", "") for b in c
                         if isinstance(b, dict) and b.get("type") == "text")
    return ""


def _first_user_prompt(lines):
    for d in lines:
        m = d.get("message") or {}
        if m.get("role") == "user":
            t = _msg_text(m)
            if t:
                return t
    return ""


def _assistant(lines):
    """(served_model, text, refused, category) — served = last REAL model (ignore the
    <synthetic> bookkeeping turns); text collected only from real-model turns."""
    served, texts, refused, category = None, [], False, None
    for d in lines:
        m = d.get("message") or {}
        if m.get("role") != "assistant":
            continue
        real = m.get("model") not in SYNTH
        if real:
            served = m.get("model")
        if m.get("stop_reason") == "refusal":
            refused = True
            category = (m.get("stop_details") or {}).get("category") or category
        if real:
            t = _msg_text(m)
            if t.strip():
                texts.append(t)
    return served, "\n\n".join(texts).strip(), refused, category


def _norm(s):
    return re.sub(r"\s+", " ", (s or "")).strip()


def _sig(s):
    return re.sub(r"[^a-z0-9]", "", (s or "").lower())[:220]


# ---------------------------------------------------------------- rendering

def _demote_headers(md, by=2):
    """Push ATX headers inside a review down `by` levels so they nest under the
    component's own H2, without mangling `#` lines inside fenced code blocks."""
    out, in_fence = [], False
    for line in md.split("\n"):
        s = line.lstrip()
        if s.startswith("```") or s.startswith("~~~"):
            in_fence = not in_fence
            out.append(line)
            continue
        if not in_fence:
            m = re.match(r"^(#{1,6})(\s+\S)", line)
            if m:
                n = min(6, len(m.group(1)) + by)
                line = "#" * n + line[len(m.group(1)):]
        out.append(line)
    return "\n".join(out)


def _render(project, usable, mode):
    name = os.path.basename(str(project).rstrip("/"))
    what = ("its actual source code" if mode == "code" else "an Opus-distilled summary")
    L = ["# Fable 5 — preliminary review\n",
         "> Generated by [scoperoute](https://github.com/botable/scoperoute) from a Claude "
         "**Fable 5** triage probe. Each section is Fable's own improvement suggestions for a "
         "component of `%s`.\n" % name,
         "> **What this is:** a *preliminary* review. scoperoute distilled each component "
         "(Sonnet 5 recon → Opus 4.8 summary%s), then asked Fable 5 to improve it. Treat it as "
         "a fast second opinion, not a line-by-line audit.\n"
         % (" + Opus-curated real code" if mode == "code" else "")]

    def sort_key(item):
        comp, v = item
        return (not (v["model"] == FABLE and not v["refused"]), comp.lower())

    for comp, v in sorted(usable.items(), key=sort_key):
        L.append("\n---\n")
        loc = " — `%s`" % v["path"] if v.get("path") else ""
        L.append("## %s%s\n" % (comp, loc))
        if v["refused"]:
            L.append("_Fable **declined** this component"
                     + (" (category: `%s`)" % v["category"] if v["category"] else "")
                     + " — for scoperoute that's the signal to keep it on Opus. No review text._\n")
            continue
        if v["model"] != FABLE:
            L.append("_Fable declined; served by `%s` (masked fallback) — a second opinion, "
                     "not a Fable review._\n" % (v["model"] or "unknown"))
        else:
            note = " · probed %d×" % v["repeats"] if v["repeats"] > 1 else ""
            L.append("_Reviewer: `claude-fable-5`%s_\n" % note)
        L.append("\n" + _demote_headers(v["text"].strip()) + "\n")
    L.append("\n---\n_Metadata-only provenance: no refusal categories/URLs are stored here._\n")
    return "\n".join(L)


# ---------------------------------------------------------------- main entry

def generate(records, workdir, no_write=False, projects_root=None):
    """Write <project>/_fable/fable-architecture-review.md for each project in `records`
    that was probed (arch/code) in this run, reading transcripts under `workdir`.
    Returns the list of written paths. `records` = this run's row dicts.
    projects_root overrides ~/.claude/projects (used by tests)."""
    sdir = T.session_dir(workdir, projects_root)
    if not Path(sdir).is_dir():
        return []

    # name2proj + mode, straight from THIS run's records (authoritative — no globbing).
    name2proj, proj_mode = {}, {}
    for rec in records:
        proj = rec.get("project")
        if not proj or rec.get("_mode") not in ("arch", "code"):
            continue
        proj_mode[proj] = rec.get("_mode")
        for c in rec.get("_components", []) or []:
            if c.get("name"):
                name2proj[c["name"]] = proj
    if not proj_mode:
        return []

    # 1) parse transcripts: summaries -> arch_md index (name, project, path); improves.
    archmd2comp, improves = {}, []
    for path in glob.glob(os.path.join(str(sdir), "*.jsonl")):
        lines = _load(path)
        if not lines:
            continue
        prompt = _first_user_prompt(lines)
        if prompt.startswith(SUMMARY_HEAD):
            blob = prompt[prompt.find("{"):]
            try:
                recon, _ = json.JSONDecoder().raw_decode(blob)
            except ValueError:
                continue
            rel = {c.get("name"): c.get("path") for c in recon.get("components", [])}
            so = _structured(lines)
            for c in (so or {}).get("components", []) or []:
                nm, md = c.get("name"), c.get("arch_md")
                if nm and md and md.strip():
                    archmd2comp[_norm(md)] = (nm, name2proj.get(nm), rel.get(nm))
        elif prompt.startswith(IMPROVE_HEAD_ARCH) or prompt.startswith(IMPROVE_HEAD_CODE):
            arch = prompt
            for marker in ("Here is the component's architecture:",):
                if marker in arch:
                    arch = arch.split(marker, 1)[1]
            # cut at the code section (code mode) or the trailing instruction (arch mode)
            for tail in ("\n\nAnd here are real excerpts", "\n\nGive your architectural",
                         "\n\nSuggest concrete improvements"):
                if tail in arch:
                    arch = arch.split(tail, 1)[0]
            served, text, refused, category = _assistant(lines)
            improves.append({"arch": arch.strip(), "model": served, "text": text,
                             "refused": refused, "category": category})

    # 2) attribute each improve to (project, component, path)
    for im in improves:
        comp, project, path = archmd2comp.get(_norm(im["arch"]), (None, None, None))
        if comp is None:
            al = im["arch"].lower()
            cands = [(nm, pr) for nm, pr in name2proj.items()
                     if nm and nm.split(" (")[0].strip().lower() in al]
            if cands:
                comp, project = max(cands, key=lambda x: len(x[0].split(" (")[0]))
        im["component"], im["project"], im["path"] = comp, project, path

    # 3) cluster per project by path (merge repeats/re-summarizations), pick best review
    written = []
    for project, mode in proj_mode.items():
        mine = [im for im in improves if im.get("project") == project]
        clusters = {}
        for im in mine:
            key = ("path:" + im["path"].rstrip("/").lower() if im.get("path")
                   else "name:" + im["component"].split(" (")[0].strip().lower()
                   if im.get("component") else "sig:" + _sig(im["arch"]))
            clusters.setdefault(key, []).append(im)
        usable = {}
        for _k, recs in clusters.items():
            best = max(recs, key=lambda r: (r["model"] == FABLE and not r["refused"],
                                            len(r["text"] or "")))
            text = best["text"] or ""
            if len(text) < 120 and not (best["refused"] and best["category"]):
                continue
            names = [r["component"] for r in recs if r.get("component")]
            title = max(names, key=len) if names else (best["arch"].split("\n")[0][:60] + "…")
            if title in usable:
                title += " [%s]" % _sig(best["arch"])[:6]
            paths = [r["path"] for r in recs if r.get("path")]
            usable[title] = {"model": best["model"], "refused": best["refused"],
                             "category": best["category"], "repeats": len(recs),
                             "text": text, "path": paths[0] if paths else None}
        real = [v for v in usable.values() if not v["refused"] and len(v["text"]) > 120]
        if not usable or not real or not os.path.isdir(project):
            continue
        if no_write:
            written.append(str(Path(project) / "_fable" / "fable-architecture-review.md"))
            continue
        outdir = Path(project) / "_fable"
        outdir.mkdir(exist_ok=True)
        f = outdir / "fable-architecture-review.md"
        f.write_text(_render(project, usable, mode), encoding="utf-8")
        written.append(str(f))
    return written


def _structured(lines):
    for d in lines:
        m = d.get("message") or {}
        if m.get("role") != "assistant":
            continue
        for b in (m.get("content") or []):
            if isinstance(b, dict) and b.get("type") == "tool_use" \
                    and b.get("name") == "StructuredOutput" and isinstance(b.get("input"), dict):
                return b["input"]
    return None
